### PR TITLE
Add Python 3.6, drop unsupported 2.6 and 3.3

### PR DESCRIPTION
**Pull request by hugovk**
Wheel has dropped support for Python 2.6 which is causing [master to fail](https://travis-ci.org/hugovk/python-unicodecsv/builds/330474737) and PRs (eg. https://github.com/jdunck/python-unicodecsv/pull/84).

Python 2.6 has been EOL for over four years, and is no longer receiving security updates:
https://en.wikipedia.org/wiki/CPython#Version_history

Python 3.3 is also EOL, and they're both little used. Here's the pip installs for unicodecsv from PyPI for last month:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   91.2% |        464,979 |
| 3.6            |    4.4% |         22,307 |
| 3.5            |    2.4% |         12,449 |
| 3.4            |    1.7% |          8,855 |
| 2.6            |    0.3% |          1,306 |
| 3.7            |    0.0% |            133 |
| 3.3            |    0.0% |             86 |
| None           |    0.0% |              1 |

Source: `pypinfo --start-date -48 --end-date -18 --percent --pip --markdown unicodecsv pyversion`

Dropping them allows the code to be modernised, and a dependency on unittest2 to be dropped.

This PR also adds Python 3.6 to the test matrix.

### CODE REVIEW

**Comment by hugovk** [comment]
Here's the pip installs for unicodecsv from PyPI for June 2018:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  87.53% |        255,663 |
| 3.6            |   8.69% |         25,373 |
| 3.5            |   2.69% |          7,870 |
| 3.4            |   0.98% |          2,855 |
| 3.7            |   0.07% |            194 |
| 2.6            |   0.04% |            128 |
| 3.3            |   0.00% |             13 |
| 3.8            |   0.00% |              1 |
| Total          |         |        292,097 |

Source: `pypinfo --start-date 2018-06-01 --end-date 2018-06-30 --percent --markdown unicodecsv pyversion`

Since December 2017:
* Python 2.6 has dropped from 1,306 (0.3%) to 128 (0.04%)
* Python 3.3 has dropped from 86 (~0.0%) to 13 (~0.00%)

@ryanhiebert Thanks for the review approval. Who else is available to review/merge?

**Comment by hugovk** [comment]
@jdunck Any thoughts on merging this? Thanks!

---

Here's the pip installs for unicodecsv from PyPI for January 2019:

| category | percent | downloads |
|----------|--------:|----------:|
|      2.7 |  74.99% | 1,058,764 |
|      3.6 |  17.49% |   246,989 |
|      3.5 |   4.72% |    66,653 |
|      3.7 |   1.96% |    27,654 |
|      3.4 |   0.63% |     8,875 |
| null     |   0.19% |     2,658 |
|      2.6 |   0.01% |       119 |
|      3.3 |   0.01% |        95 |
| Total    |         | 1,411,807 |

Source: `pypistats python_minor unicodecsv --last-month`

**Comment by Jamim** [comment]
Hi @hugovk,

I think it would be great to have this PR merged. And it's also worth to add Python 3.7 as well.
But I see that there was no activity in this repository for a few years, so this project is probably abandoned.

Anyway, thank you for the effort, @hugovk!

**Comment by hugovk** [comment]
Thanks, I've added Python 3.7!

**Comment by alingse** [comment]
LGTM

**Comment by allan-simon** [comment]
@jdotjdot  , any chance of getting this PR merged to keep your library at least running with recent python versions, would be awesome for those relying on your work  (or maybe opening merging right to some other contributors so that you don't need to care about it anymore ?)  :)

**Comment by jdotjdot** [comment]
@allan-simon don't think you mean me? This isn't my library (though I did fork it)

**Comment by allan-simon** [comment]
yes sorry wrong @ :/ ,   @jdunck  I meant

**Comment by Jamim** [comment]
Hello @allan-simon,

I've just created [an issue about the project maintenance](https://github.com/jdunck/python-unicodecsv/issues/92), so you can share your thoughts there.

**Comment by hugovk** [comment]
Python 3.4 is now also EOL (since 2019-03-16) and little used. July 2019 stats:

| category | percent | downloads |
|----------|--------:|----------:|
| 2.7      |  68.28% | 1,139,429 |
| 3.6      |  18.00% |   300,460 |
| 3.7      |   7.11% |   118,586 |
| 3.5      |   5.52% |    92,054 |
| null     |   0.85% |    14,259 |
| 3.4      |   0.23% |     3,822 |
| 3.8      |   0.01% |       102 |
| 3.3      |   0.00% |        79 |
| 2.6      |   0.00% |        34 |
| Total    |         | 1,668,825 |

Source: `pip install -U pypistats && pypistats python_minor unicodecsv --last-month`

Shall we drop that too?

**Comment by hugovk** [comment]
Closing, see https://github.com/jdunck/python-unicodecsv/issues/92 and https://python3statement.org.

Please ping me if you'd like me it revived for merge, or a smaller change that only adds 3.7 (and 3.8 now!).

---

Here's the pip installs for unicodecsv from PyPI for September 2019:

| category | percent | downloads |
|----------|--------:|----------:|
| 2.7      |  63.04% |   936,546 |
| 3.6      |  21.19% |   314,865 |
| 3.7      |   9.14% |   135,837 |
| 3.5      |   5.65% |    83,907 |
| null     |   0.86% |    12,802 |
| 3.4      |   0.10% |     1,550 |
| 3.8      |   0.00% |        40 |
| 2.6      |   0.00% |        19 |
| Total    |         | 1,485,566 |

Date range: 2019-09-01 - 2019-09-30

Source: `pip install -U pypistats && pypistats python_minor unicodecsv --last-month`

**Pull request closed without merging**
